import{a as g,i,S as v}from"./assets/vendor-f144e563.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const w="41636185-b642aedee9ddf38a3f46d8b56";g.defaults.baseURL="https://pixabay.com";const h=(s,t=1,o=15)=>{try{return g("/api/",{params:{key:w,q:s,page:t,per_page:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}})}catch{i.error({title:"Error",message:`Something went wrong. ${error.message}`})}},y=s=>s.reduce((t,{largeImageURL:o,webformatURL:n,tags:e,likes:r,views:l,comments:b,downloads:L})=>t+`<li class="gallery-item">
        <a href=${o}> 
          <img class="gallery-img" src=${n} alt="${e}"/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${r}</span></p>
          <p>Views: <span class="text-value">${l}</span></p>
          <p>Comments: <span class="text-value">${b}</span></p>
          <p>Downloads: <span class="text-value">${L}</span></p>
        </div>
      </li>`,""),S=document.querySelector(".form"),f=document.querySelector(".gallery"),x=document.getElementById("search-input"),d=document.querySelector(".loader"),a=document.querySelector(".page-btn");let c=1,u=null,m=0,p;d.classList.add("hidden");a.classList.add("hidden");const E=async s=>{if(s.preventDefault(),u=x.value.trim(),!u)return i.info({message:"Please enter text",position:"topCenter"});c=1,m=0,d.classList.remove("hidden"),a.classList.add("hidden"),f.innerHTML="";try{const t=await h(u,c),{hits:o,totalHits:n}=t.data;if(m=n,o.length>0)f.innerHTML=y(o),p||(p=new v(".gallery a",{nav:!0,captionsData:"alt",captionDelay:250,close:!0,enableKeyboard:!0,docClose:!0}),p.refresh()),m>15&&a.classList.remove("hidden");else return i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})}catch(t){console.error("Error:",t),i.error({message:"An error occurred. Try again later.",position:"topCenter"})}finally{d.classList.add("hidden")}};S.addEventListener("submit",E);const q=async()=>{a.disabled=!0,c+=1,d.classList.remove("hidden");try{const s=await h(u,c),{hits:t}=s.data;if(t.length>0){const o=y(t);f.insertAdjacentHTML("beforeend",o),p.refresh();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:e*2,behavior:"smooth"}),m<=c*15?(a.classList.add("hidden"),i.info({title:"No more info",message:"We're sorry, but you've reached the end of search results."})):a.disabled=!1}else i.info({title:"No more results",message:"No additional images found."}),a.disabled=!1}catch(s){i.error({title:"Error",message:`Something went wrong. ${s.message}`}),a.disabled=!1}finally{d.classList.add("hidden")}};a.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
