import{a as g,i as n,S as v}from"./assets/vendor-f144e563.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const w="41636185-b642aedee9ddf38a3f46d8b56";g.defaults.baseURL="https://pixabay.com";const h=(s,t=1,o=15)=>{try{return g("/api/",{params:{key:w,q:s,page:t,per_page:o,image_type:"photo",orientation:"horizontal",safesearch:"true"}})}catch{n.error({title:"Error",message:`Something went wrong. ${error.message}`})}},y=s=>s.reduce((t,{largeImageURL:o,webformatURL:a,tags:e,likes:r,views:i,comments:L,downloads:b})=>t+`<li class="gallery-item">
        <a href=${o}> 
          <img class="gallery-img" src=${a} alt="${e}"/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${r}</span></p>
          <p>Views: <span class="text-value">${i}</span></p>
          <p>Comments: <span class="text-value">${L}</span></p>
          <p>Downloads: <span class="text-value">${b}</span></p>
        </div>
      </li>`,""),S=document.querySelector(".form"),p=document.querySelector(".gallery"),x=document.getElementById("search-input"),l=document.querySelector(".loader"),c=document.querySelector(".page-btn");let d=1,u=null,f=0,m;l.classList.add("hidden");c.classList.add("hidden");const E=async s=>{if(s.preventDefault(),u=x.value.trim(),!u)return n.info({message:"Please enter text",position:"topCenter"});l.classList.remove("hidden"),c.classList.add("hidden"),p.innerHTML="";try{const t=await h(u,d),{hits:o,totalHits:a}=t.data;if(f=a,o.length>0)p.innerHTML=y(o),m||(m=new v(".gallery a",{nav:!0,captionsData:"alt",captionDelay:250,close:!0,enableKeyboard:!0,docClose:!0})),m.refresh(),f>15&&c.classList.remove("hidden");else return n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})}catch(t){console.error("Error:",t),n.error({message:"An error occurred. Try again later.",position:"topCenter"})}finally{l.classList.add("hidden")}};S.addEventListener("submit",E);const q=async()=>{d+=1,l.classList.remove("hidden");try{const s=await h(u,d),{hits:t}=s.data;if(t.length>0){const o=y(t);p.insertAdjacentHTML("beforeend",o),m.refresh();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:e*2,behavior:"smooth"}),f<=d*15&&(c.classList.add("hidden"),n.info({title:"No more info",message:"We're sorry, but you've reached the end of search results."}))}else n.info({title:"No more results",message:"No additional images found."})}catch(s){n.error({title:"Error",message:`Something went wrong. ${s.message}`})}finally{l.classList.add("hidden")}};c.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
